# EXPERIMENT 6

## Aim:
## Implementation of Artificial Neural Network algorithm using Tensorflow

Upload the dataset

Import numpy as np, pandas as pd and tensorflow as tf

In [19]:
# import numpy as np
# import pandas as pd
import numpy as np
import pandas as pd
import tensorflow as tf

Read the dataset, observe its five rows, leave redundant columns and make x and y

In [20]:
data = pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Data Preprocessing

Encoding categorical data using Lable Encoder

In [21]:
X = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [22]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le1.fit(X[:,2])
X[:,2] = le1.transform(X[:,2]) 

One Hot Encoding the "Geography" column using ColumnTransformer and OneHotEncoder

In [23]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the dataset into the Training set and Test set

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:] = sc.fit_transform(X_train[:,:])

X_test[:,:] = sc.transform(X_test[:,:])

Building the ANN

In [26]:
ann = tf.keras.models.Sequential()

Adding the first hidden layer

In [27]:
ann.add(tf.keras.layers.Dense(4,activation='relu'))

Adding the second hidden layer

In [28]:
ann.add(tf.keras.layers.Dense(3,activation='relu'))

Adding the output layer

In [29]:
ann.add(tf.keras.layers.Dense(1,activation='sigmoid'))

Compiling the ANN

In [30]:
ann.compile(optimizer='adam', loss='binary_crossentropy')

Training the ANN on the Training set

In [31]:
X_train = np.asarray(X_train).astype(np.float32)
Y_train = np.asarray(y_train).astype(np.float32)
ann.fit(X_train, y_train,batch_size=32, epochs=10)

Epoch 1/10
235/235 [==============================] - 1s 1ms/step - loss: 0.5791
Epoch 2/10
235/235 [==============================] - 0s 1ms/step - loss: 0.5096
Epoch 3/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4763
Epoch 4/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4545
Epoch 5/10
235/235 [==============================] - 0s 2ms/step - loss: 0.4402
Epoch 6/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4306
Epoch 7/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4234
Epoch 8/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4175
Epoch 9/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4130
Epoch 10/10
235/235 [==============================] - 0s 1ms/step - loss: 0.4094


Making the predictions and evaluating the model

In [32]:
X_test = np.asarray(X_test).astype(np.float32)
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
cm


array([[1920,   51],
       [ 393,  136]], dtype=int64)

In [34]:
score = accuracy_score(y_test,y_pred)
score

0.8224

# Conclusion:
In this experiment, we understood and implemented Artificial Neural Network algorithm using Tensorflow.
In this model we formed two hidden layers with 4 and 3 neurons respectively.